version: "3.8"
services:
  postgres:
    container_name: projects-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - projects-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  projects-postgres-data:
